### ISSUE TITLE
Consider upstreaming?

### ISSUE THREAD

**Issue by printfn** [beeftornado/homebrew-rmtree#51]
I find this formula really useful, and was wondering whether it would be possible to put it in into `homebrew/core` or something like that?

I don't know if this meets their eligibility requirements or if it's even possible, but it would be nice to not have to add this custom tap to be able to use the `rmtree` command.

**Comment by caseyduquettesc** [comment]
There was a discussion many years back, which is what initiated created this command. IIRC, they didn't want to maintain it because of the dangers associated with guessing what's not needed. Back then, homebrew wasn't keeping track of what was explicitly installed by the user versus implicitly installed by another program and so just removing anything that had no dependents at the time, was risky (hence the warning in the readme).

I don't work on homebrew or am even familiar with it's code past 2017, however it would _appear_ that near the beginning of 2021, homebrew added a new command called `autoremove`. [ref](https://docs.brew.sh/Manpage#autoremove---dry-run) [ref2](https://github.com/Homebrew/brew/commits/1fd4c4d840778b7679e49a9eaecf67da0dfc1172/Library/Homebrew/cmd/autoremove.rb) So it would seem they decided to go the direction of aptitude where you have to delete the package you want first, and then ask homebrew to do a cleanup.

**Comment by printfn** [comment]
Interesting, thanks for that explanation!
