### ISSUE TITLE
Not removing all dependencies.

### ISSUE THREAD

**Issue by Zegnat** [beeftornado/homebrew-rmtree#6]
The README warns that `rmtree` might remove too much, but in my case it seems to be removing too little:

```
$ brew list
brew-cask     brew-rmtree   youtube-dl
$ brew install mpv-player/mpv/mpv
$ brew rmtree mpv-player/mpv/mpv
$ brew list
brew-cask     glib          little-cms2
brew-rmtree   jpeg          lua
cairo         libffi        mpg123
fontconfig    libpng        pixman
freetype      libtiff       pkg-config
gettext       libvo-aacenc  youtube-dl
```

Can anything be done about this?

**Comment by beeftornado** [comment]
Interesting, I'll take a look later. Off the top of my head, if a project doesn't list any dependencies in its formula then there isn't anything that can be done besides updating the formula.

**Comment by beeftornado** [comment]
Thanks for reporting this issue! It turns out that if a formula has dependencies that aren't in the official homebrew repository, meaning they exist in a tap, it sort of throws off everything. The reason for this, is that homebrew places these dependencies in different places in its output from the different commands rmtree needs to execute. The sorting order was assumed to be the same. I've raised an issue with homebrew about this, and in addition I will update rmtree to sort the lists itself. This will resolve your issue.

**Comment by Zegnat** [comment]
Thanks for looking into this!
